name: Get latest awsebcli

on:
  workflow_dispatch:
  schedule:
    - cron:  '0 4 * * 3'
  push:
    branches: [ 'master' ]

jobs:
  version:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
    - uses: actions/checkout@v3

    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"

    - name: Get awsebcli version
      run: |
        python -m pip index versions awsebcli | grep awsebcli | egrep -o '[0-9\.]+' > VERSION && echo "ebver=$(cat VERSION)" >> $GITHUB_ENV

    - uses: stefanzweifel/git-auto-commit-action@v4
      with:
        commit_message: ${{ env.ebver }}
        tagging_message: ${{ format('v{0}', env.ebver) }}
